### PR TITLE
Add .python-version file for ST 4

### PR DESCRIPTION
**Pull request by themilkman**
Hi @ned-martin,

first of all thanks for this nice plugin!

With this PR ST4 will use the new Python 3.8 plugin-host instead of the old 3.3.
Older ST versions keep using the 3.3, thus this should be 100% backward compatible.
I've been using this locally for quite a while now.
The second commit simply adds v4 to the Readme.

Cheers!

### CODE REVIEW

**Comment by themilkman** [comment]
Hi @ned-martin, thanks for the merge! Do you plan to release a new version in the foreseeable future? :-)

**Comment by themilkman** [comment]
Hi @ned-martin, just wanted to ask again regarding releasing a new version :-) Thanks in advance!

**Comment by ned-martin** [comment]
Thanks for the fix. I've updated the version.

**Comment by themilkman** [comment]
Thank you very much!

**Pull request merged**
